In [1]:
import pandas as pd

In [2]:
#loading data
blinkit   = pd.read_csv("blinkit_mock_export.csv")
zepto     = pd.read_csv("zepto_mock_export.csv")
instamart = pd.read_csv("instamart_mock_export.csv")

In [3]:
blinkit.head()

,internal_id,product_name,units_sold,revenue_inr,date,city
0,BLK1000,Lays Classic Salted 26g,24,702.05,05-04-2025,Mumbai
1,BLK1001,LAYS CLASSIC SALTED,24,1738.86,19-04-2025,New Delhi
2,BLK1002,Too Yumm Multigrain Crisps 60g,1,16.56,17-04-2025,Mumbai
3,BLK1003,Haldirams Aloo Bhujia 200g,18,430.54,14-04-2025,Chennai
4,BLK1004,kurkure masala munch - 90gm,19,559.99,25-04-2025,Delhi

In [4]:
zepto.head()

                        item_name  qty_sold      gmv        date   location
0  Too Yumm Multigrain Crisps 60g        13   371.33  2025/04/10  Hyderabad
1                HALDIRAMS BHUJIA        23  1013.54  2025/04/10     Mumbai
2             LAYS CLASSIC SALTED        24      NaN  2025/04/02  Bangalore
3             TOO YUMM MULTIGRAIN        17   357.34  2025/04/03    Chennai
4             LAYS CLASSIC SALTED         3   171.79  2025/04/13     Mumbai

In [5]:
instamart.head()

,sku_description,quantity,sales_value,date,region,remarks
0,oreo cream biscuits 120gm,11,797.63,April 05 2025,New Delhi,NaN
1,TOO YUMM MULTIGRAIN,5,297.25,April 14 2025,New Delhi,NaN
2,haldiram aloo bhujia - 200gm,14,201.02,April 13 2025,Bengaluru,NaN
3,HALDIRAMS BHUJIA,0,69.97,April 16 2025,Bengaluru,NaN
4,oreo cream biscuits 120gm,25,932.48,April 18 2025,Bengaluru,NaN

In [6]:
#renaming columns for better readabililty and maintain standardized formats

blinkit = blinkit.rename(columns={
    "product_name" : "product_name",
    "units_sold"   : "units_sold",
    "revenue_inr"  : "revenue_inr",
    "date"         : "date",
    "city"         : "city"
})

zepto = zepto.rename(columns={
    "item_name" : "product_name",
    "qty_sold"  : "units_sold",
    "gmv"       : "revenue_inr",
    "date"      : "date",
    "location"  : "city"
})

instamart = instamart.rename(columns={
    "sku_description" : "product_name",
    "quantity"        : "units_sold",
    "sales_value"     : "revenue_inr",
    "date"            : "date",
    "region"          : "city"
})


blinkit.drop(columns=["internal_id"], errors="ignore", inplace = True)
instamart.drop(columns=["remarks"], errors="ignore", inplace = True)

In [7]:
# adding platform columns will help in the master CSV
blinkit["platform"]   = "Blinkit"
zepto["platform"]     = "Zepto"
instamart["platform"] = "Instamart"

# making all date formats same, writing current format for my convenience
# Blinkit:   DD-04-2025  
# Zepto:     2025/04/10  
# Instamart: April 05 2025 

blinkit["date"]   = pd.to_datetime(blinkit["date"],   dayfirst=True)
zepto["date"]     = pd.to_datetime(zepto["date"],     yearfirst=True)
instamart["date"] = pd.to_datetime(instamart["date"], format="%B %d %Y")


for df in [blinkit, zepto, instamart]:
    df["date"] = df["date"].dt.strftime("%d-%m-%Y")

# city name changes
city_map = {
    "delhi"     : "Delhi",
    "new delhi" : "Delhi",
    "New Delhi" : "Delhi",
    "bangalore" : "Bengaluru",
    "Bangalore" : "Bengaluru",
    "mumbai"    : "Mumbai",
    "hyderabad" : "Hyderabad",
    "chennai"   : "Chennai"
}

for df in [blinkit, zepto, instamart]:
    df["city"] = df["city"].str.strip().replace(city_map)

In [8]:
zepto.head()

,product_name,units_sold,revenue_inr,date,city,platform
0,Too Yumm Multigrain Crisps 60g,13,371.33,10-04-2025,Hyderabad,Zepto
1,HALDIRAMS BHUJIA,23,1013.54,10-04-2025,Mumbai,Zepto
2,LAYS CLASSIC SALTED,24,NaN,02-04-2025,Bengaluru,Zepto
3,TOO YUMM MULTIGRAIN,17,357.34,03-04-2025,Chennai,Zepto
4,LAYS CLASSIC SALTED,3,171.79,13-04-2025,Mumbai,Zepto

In [9]:
blinkit.head()

,product_name,units_sold,revenue_inr,date,city,platform
0,Lays Classic Salted 26g,24,702.05,05-04-2025,Mumbai,Blinkit
1,LAYS CLASSIC SALTED,24,1738.86,19-04-2025,Delhi,Blinkit
2,Too Yumm Multigrain Crisps 60g,1,16.56,17-04-2025,Mumbai,Blinkit
3,Haldirams Aloo Bhujia 200g,18,430.54,14-04-2025,Chennai,Blinkit
4,kurkure masala munch - 90gm,19,559.99,25-04-2025,Delhi,Blinkit

In [10]:
instamart.head()

,product_name,units_sold,revenue_inr,date,city,platform
0,oreo cream biscuits 120gm,11,797.63,05-04-2025,Delhi,Instamart
1,TOO YUMM MULTIGRAIN,5,297.25,14-04-2025,Delhi,Instamart
2,haldiram aloo bhujia - 200gm,14,201.02,13-04-2025,Bengaluru,Instamart
3,HALDIRAMS BHUJIA,0,69.97,16-04-2025,Bengaluru,Instamart
4,oreo cream biscuits 120gm,25,932.48,18-04-2025,Bengaluru,Instamart

In [11]:

# product name standardization
product_map = {
    # Lays 
    "Lays Classic Salted 26g"    : "Lays Classic Salted 26g",
    "LAYS CLASSIC SALTED"        : "Lays Classic Salted 26g",
    "lay's classic - 26gm"       : "Lays Classic Salted 26g",
    "lays classic salted"        : "Lays Classic Salted 26g",

    # Kurkure 
    "kurkure masala munch - 90gm": "Kurkure Masala Munch 90g",
    "KURKURE MASALA MUNCH"       : "Kurkure Masala Munch 90g",
    "Kurkure Masala Munch 90g"   : "Kurkure Masala Munch 90g",

    # Oreo 
    "Oreo Original Cream 120g"   : "Oreo Original Cream 120g",
    "OREO ORIGINAL"              : "Oreo Original Cream 120g",
    "oreo cream biscuits 120gm"  : "Oreo Original Cream 120g",

    # Too Yumm 
    "Too Yumm Multigrain Crisps 60g" : "Too Yumm Multigrain Crisps 60g",
    "TOO YUMM MULTIGRAIN"            : "Too Yumm Multigrain Crisps 60g",
    "too yumm crisps 60gm"           : "Too Yumm Multigrain Crisps 60g",

    # Haldirams 
    "Haldirams Aloo Bhujia 200g"     : "Haldirams Aloo Bhujia 200g",
    "HALDIRAMS BHUJIA"               : "Haldirams Aloo Bhujia 200g",
    "haldiram aloo bhujia - 200gm"   : "Haldirams Aloo Bhujia 200g",
}

for df in [blinkit, zepto, instamart]:
    df["product_name"] = df["product_name"].str.strip().replace(product_map)

# DATA QUALIITY HANDLING, LIKE NULL VALUES AND ADDING FLAGS FOR FASTER IDENTIFICATION OF NULL VALUE ROWS
zepto["data_quality_flag"] = zepto["revenue_inr"].isna().map(
    {True: "missing_revenue", False: "ok"}
)
blinkit["data_quality_flag"]   = "ok"
instamart["data_quality_flag"] = instamart["units_sold"].apply(
    lambda x: "zero_quantity" if x == 0 else "ok"
)

In [12]:
zepto.head()

,product_name,units_sold,revenue_inr,date,city,platform,data_quality_flag
0,Too Yumm Multigrain Crisps 60g,13,371.33,10-04-2025,Hyderabad,Zepto,ok
1,Haldirams Aloo Bhujia 200g,23,1013.54,10-04-2025,Mumbai,Zepto,ok
2,Lays Classic Salted 26g,24,NaN,02-04-2025,Bengaluru,Zepto,missing_revenue
3,Too Yumm Multigrain Crisps 60g,17,357.34,03-04-2025,Chennai,Zepto,ok
4,Lays Classic Salted 26g,3,171.79,13-04-2025,Mumbai,Zepto,ok

In [15]:
#now making a standardized master csv
final_cols = ["platform", "product_name", "units_sold",
              "revenue_inr", "date", "city", "data_quality_flag"]

blinkit   = blinkit[final_cols]
zepto     = zepto[final_cols]
instamart = instamart[final_cols]

# ── 9. CONCATENATE AND EXPORT ─────────────────────────────────────────────────
master_df = pd.concat([blinkit, zepto, instamart], ignore_index=True)
master_df["date"] = pd.to_datetime(master_df["date"], format="%d-%m-%Y").dt.strftime("%Y-%m-%d")

master_df.to_csv("unified_output.csv", index=False)
print("\n✓ unified_output.csv saved successfully.")

✓ unified_output.csv saved successfully.